[main]
font=Inter:size=11.5:fontfeatures=ss03:fontfeatures=tnum,Material Symbols Filled:size=11.5
dpi-aware=no
terminal=kitty
# Spotlight-like, upper third of the screen
anchor=top
y-margin=240
width=66
lines=7
# in points, not pixels (28pt is about 37px)
line-height=28
horizontal-pad=16
vertical-pad=12
inner-pad=8
image-size-ratio=0.8
include=~/.config/fuzzel/colors.ini

[border]
radius=26
selection-radius=9
