[main]
font=Inter:size=12:fontfeatures=ss03:fontfeatures=tnum,Material Symbols Filled:size=12
dpi-aware=no
terminal=kitty
# Spotlight-like, upper third of the screen
anchor=top
y-margin=240
width=66
lines=7
line-height=40
horizontal-pad=20
vertical-pad=16
inner-pad=10
image-size-ratio=0.8
include=~/.config/fuzzel/colors.ini

[border]
radius=32
selection-radius=11
