background #000000
foreground #e6e6e6
cursor #e6e6e6
selection_background #333333
selection_foreground #ffffff
color0  #2e2e2e
color8  #808080
color1  #f66151
color9  #ff8a80
color2  #57e389
color10 #8ff0a4
color3  #e5a50a
color11 #f8e45c
color4  #62a0ea
color12 #99c1f1
color5  #c061cb
color13 #dc8add
color6  #4fc8c8
color14 #93dddd
color7  #c0c0c0
color15 #ffffff
